### ISSUE TITLE
Validation: use typescript declaration file instead of json schema

### ISSUE THREAD

**Issue by DrSensor** [DrSensor/webassembly-loader#1]
Replace [options.json][] with options.d.ts using: 
- https://github.com/YousefED/typescript-json-schema programmatically
- _or_ https://quicktype.io/ **if in the future** they have a programmable API, rollup-plugin, or webpack-loader

After that, it needs to be implemented in
https://github.com/DrSensor/webassembly-loader/blob/888c1b8f9cc6e9c0d7375d83b3a9ee277af3c6e5/src/index.ts#L5
https://github.com/DrSensor/webassembly-loader/blob/888c1b8f9cc6e9c0d7375d83b3a9ee277af3c6e5/src/index.ts#L15-L19

> another reference https://github.com/Morglod/ts-code-info

[options.json]: https://github.com/DrSensor/webassembly-loader/blob/feature/export-mode/src/options.json

**Comment by caseyWebb** [comment]
I've got this one
