### ISSUE TITLE
wasm-bindgen example

### ISSUE THREAD

**Issue by maksnester** [DrSensor/webassembly-loader#17]
Hello @DrSensor. Could you please provide a more advanced example, something like that:

```[lang=rust]
extern crate wasm_bindgen;

use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub extern fn hello_world(mut first_name: &str, mut last_name: &str) -> String {
    // This is fairly silly code but it is just an example...
    if first_name.is_empty() {
        first_name = "John";
    }
    if last_name.is_empty() {
        last_name = "Doe";
    }
    format!("Hello, {} {}!", first_name, last_name)
}
```

Though I was able to use inlining with simple rust function from your example, I couldn't make it work for something which uses wasm_bindgen. So if it's possible, could you please provide an example of how to configure it? I would like to inline wasm into js bundle during the build. 

Thanks in advance!

UPD: tried to come up with it by myself but without success, here is a repo based on example from this repo https://github.com/maksnester/inline-wasm-with-wasm-bindgen

**Comment by DrSensor** [comment]
Note that support for `wasm_bindgen` [still experimental](https://github.com/dflemstr/rust-native-wasm-loader/blob/master/README.md#wasm-bindgen-experimental-support) in rust-native-wasm-loader.
Does your example works when replacing webassembly-loader with babel-loader?

Also, `wasm_bindgen` produce Javascript, _not_ Wasm. So this loader alone would likely not works.
